package com.truebubble.ui.strings

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    val langCode: String,
    // Nav
    val poziomica: String,
    val libella: String,
    // Top bar buttons
    val menuBtn: String,
    val settingsBtn: String,
    val closeBtn: String,
    // Level screen
    val longitudinal: String,
    val transverse: String,
    val remember: String,
    val clear: String,
    val calibrated: String,
    val notCalibrated: String,
    val rememberedLine: String,
    // Settings
    val settingsTitle: String,
    val back: String,
    val appearance: String,
    val theme: String,
    val dark: String,
    val light: String,
    val highContrastLabel: String,
    val highContrastSub: String,
    val bubbleColorLabel: String,
    val levelSignal: String,
    val soundOnLevel: String,
    val soundOnLevelSub: String,
    val vibrateOnLevel: String,
    val vibrateOnLevelSub: String,
    val sensors: String,
    val calibrateSensors: String,
    // Calibration
    val calibrationTitle: String,
    val howToCalibrate: String,
    val instrStep1: String,
    val instrStep2: String,
    val instrStep3: String,
    val instrStep4: String,
    val autoCalibration: String,
    val startCalibration: String,
    val calibrating: String,
    val calibratedSuccess: String,
    val manualCorrection: String,
    val pitchAxisLabel: String,
    val rollAxisLabel: String,
    val lastCalibration: String,
    val resetCalibration: String,
    // Menu
    val menuTitle: String,
    val supportTitle: String,
    val supportText: String,
    val securityTitle: String,
    val securityText: String,
    val gdprTitle: String,
    val gdprText: String,
    val contactTitle: String,
    val copiedToClipboard: String,
    val compatTitle: String,
)

val LocalAppStrings = compositionLocalOf { stringsFor("en") }

data class LangItem(val code: String, val flag: String, val name: String)

val supportedLanguages = listOf(
    LangItem("pl", "🇵🇱", "Polski"),
    LangItem("en", "🇬🇧", "English"),
    LangItem("es", "🇪🇸", "Español"),
    LangItem("de", "🇩🇪", "Deutsch"),
    LangItem("fr", "🇫🇷", "Français"),
    LangItem("pt", "🇧🇷", "Português (BR)"),
    LangItem("ar", "🇸🇦", "العربية"),
    LangItem("ru", "🇷🇺", "Русский"),
    LangItem("id", "🇮🇩", "Bahasa Indonesia"),
    LangItem("ja", "🇯🇵", "日本語"),
)

fun flagFor(code: String): String = supportedLanguages.find { it.code == code }?.flag ?: "🌐"

@Suppress("LongMethod")
fun stringsFor(code: String): AppStrings = when (code) {

    "pl" -> AppStrings(
        langCode = "pl", poziomica = "Poziomica", libella = "Libella",
        menuBtn = "Menu", settingsBtn = "Ustawienia", closeBtn = "Zamknij",
        longitudinal = "WZDŁUŻNIE", transverse = "POPRZECZNIE",
        remember = "Zapamiętaj", clear = "Wyczyść",
        calibrated = "Skalibrowano", notCalibrated = "Nieskalibrowano",
        rememberedLine = "Zapamiętano",
        settingsTitle = "Ustawienia", back = "Wstecz",
        appearance = "WYGLĄD", theme = "Motyw", dark = "Ciemny", light = "Jasny",
        highContrastLabel = "Duży kontrast łezki",
        highContrastSub = "Zwiększa widoczność (większa przezroczystość)",
        bubbleColorLabel = "Kolor łezki",
        levelSignal = "SYGNAŁ POZIOMU",
        soundOnLevel = "Dźwięk przy poziomie", soundOnLevelSub = "Sygnał przy osiągnięciu 0°",
        vibrateOnLevel = "Wibracja przy poziomie", vibrateOnLevelSub = "Wibracja przy osiągnięciu 0°",
        sensors = "CZUJNIKI", calibrateSensors = "Kalibracja czujników",
        calibrationTitle = "Kalibracja", howToCalibrate = "JAK KALIBROWAĆ",
        instrStep1 = "Połóż klasyczną poziomicę na płaskiej powierzchni.",
        instrStep2 = "Połóż telefon płasko obok poziomicy na tej samej powierzchni.",
        instrStep3 = "Poczekaj aż bąbelek poziomicy się ustabilizuje.",
        instrStep4 = "Naciśnij 'Rozpocznij kalibrację' — telefon zapamięta to ustawienie.",
        autoCalibration = "KALIBRACJA AUTOMATYCZNA",
        startCalibration = "Rozpocznij kalibrację", calibrating = "Kalibrowanie…",
        calibratedSuccess = "Skalibrowano pomyślnie",
        manualCorrection = "RĘCZNA KOREKTA",
        pitchAxisLabel = "Oś wzdłużna (Pitch)", rollAxisLabel = "Oś poprzeczna (Roll)",
        lastCalibration = "Ostatnia kalibracja", resetCalibration = "Resetuj kalibrację",
        menuTitle = "Menu",
        supportTitle = "Wsparcie projektu",
        supportText = "TrueBubble jest w pełni darmową aplikacją, wolną od reklam i ukrytych opłat. Tworzymy ją z pasji i chcemy, żeby była dostępna dla każdego.\n\nJeśli aplikacja okazała się dla Ciebie przydatna i chciałbyś wesprzeć dalszy rozwój projektu, odwiedź naszą stronę — każde wsparcie, nawet symboliczne, pozwala nam rozwijać TrueBubble i dodawać nowe funkcje.\n\nDziękujemy za korzystanie z TrueBubble!",
        securityTitle = "Bezpieczeństwo i prywatność",
        securityText = "Aplikacja TrueBubble nie zbiera żadnych danych osobowych. Wszystkie dane (kalibracja, ustawienia) są przechowywane wyłącznie lokalnie na urządzeniu i nie są wysyłane na żadne serwery zewnętrzne.",
        gdprTitle = "RODO i poufność danych",
        gdprText = "Zgodnie z Rozporządzeniem RODO (EU 2016/679):\n\n• Aplikacja nie przetwarza danych osobowych.\n• Nie są stosowane pliki cookies ani śledzenie.\n• Dane kalibracji i ustawień są w pełni pod kontrolą użytkownika.\n• Odinstalowanie aplikacji usuwa wszystkie dane.",
        contactTitle = "Kontakt",
        copiedToClipboard = "Skopiowano do schowka",
        compatTitle = "Zgodność z Android",
    )

    "es" -> AppStrings(
        langCode = "es", poziomica = "Nivel", libella = "Nivel circular",
        menuBtn = "Menú", settingsBtn = "Ajustes", closeBtn = "Cerrar",
        longitudinal = "LONGITUDINAL", transverse = "TRANSVERSAL",
        remember = "Recordar", clear = "Borrar",
        calibrated = "Calibrado", notCalibrated = "Sin calibrar",
        rememberedLine = "Recordado",
        settingsTitle = "Ajustes", back = "Atrás",
        appearance = "APARIENCIA", theme = "Tema", dark = "Oscuro", light = "Claro",
        highContrastLabel = "Burbuja alto contraste",
        highContrastSub = "Mejora la visibilidad (mayor opacidad)",
        bubbleColorLabel = "Color de burbuja",
        levelSignal = "SEÑAL DE NIVEL",
        soundOnLevel = "Sonido al nivelar", soundOnLevelSub = "Señal al alcanzar 0°",
        vibrateOnLevel = "Vibración al nivelar", vibrateOnLevelSub = "Vibración al alcanzar 0°",
        sensors = "SENSORES", calibrateSensors = "Calibrar sensores",
        calibrationTitle = "Calibración", howToCalibrate = "CÓMO CALIBRAR",
        instrStep1 = "Coloca un nivel de burbuja en una superficie plana.",
        instrStep2 = "Pon el teléfono plano junto al nivel en la misma superficie.",
        instrStep3 = "Espera a que la burbuja del nivel se estabilice.",
        instrStep4 = "Toca 'Iniciar calibración' — el teléfono guardará este ajuste.",
        autoCalibration = "CALIBRACIÓN AUTOMÁTICA",
        startCalibration = "Iniciar calibración", calibrating = "Calibrando…",
        calibratedSuccess = "Calibrado con éxito",
        manualCorrection = "CORRECCIÓN MANUAL",
        pitchAxisLabel = "Eje longitudinal (Pitch)", rollAxisLabel = "Eje transversal (Roll)",
        lastCalibration = "Última calibración", resetCalibration = "Restablecer calibración",
        menuTitle = "Menú",
        supportTitle = "Apoyar el proyecto",
        supportText = "TrueBubble es completamente gratuita y sin anuncios. La creamos con pasión para que esté disponible para todos.\n\nSi la encuentras útil y deseas apoyar el desarrollo del proyecto, visita nuestra página — cualquier apoyo, incluso simbólico, nos ayuda a mejorar TrueBubble.\n\n¡Gracias por usar TrueBubble!",
        securityTitle = "Seguridad y privacidad",
        securityText = "TrueBubble no recopila datos personales. Todos los datos (calibración, ajustes) se almacenan únicamente de forma local en tu dispositivo y nunca se envían a servidores externos.",
        gdprTitle = "RGPD y confidencialidad",
        gdprText = "De acuerdo con el Reglamento RGPD (EU 2016/679):\n\n• La app no procesa datos personales.\n• No se usan cookies ni seguimiento.\n• Los datos de calibración están bajo el control del usuario.\n• Desinstalar la app elimina todos los datos.",
        contactTitle = "Contacto",
        copiedToClipboard = "Copiado al portapapeles",
        compatTitle = "Compatibilidad con Android",
    )

    "de" -> AppStrings(
        langCode = "de", poziomica = "Wasserwaage", libella = "Libelle",
        menuBtn = "Menü", settingsBtn = "Einstellungen", closeBtn = "Schließen",
        longitudinal = "LÄNGSNEIGUNG", transverse = "QUERNEIGUNG",
        remember = "Merken", clear = "Löschen",
        calibrated = "Kalibriert", notCalibrated = "Nicht kalibriert",
        rememberedLine = "Gemerkt",
        settingsTitle = "Einstellungen", back = "Zurück",
        appearance = "AUSSEHEN", theme = "Thema", dark = "Dunkel", light = "Hell",
        highContrastLabel = "Hoher Kontrast Blase",
        highContrastSub = "Verbessert Sichtbarkeit (höhere Opazität)",
        bubbleColorLabel = "Blasenfarbe",
        levelSignal = "NIVEAU-SIGNAL",
        soundOnLevel = "Ton bei Niveau", soundOnLevelSub = "Signal bei Erreichen von 0°",
        vibrateOnLevel = "Vibration bei Niveau", vibrateOnLevelSub = "Vibration bei Erreichen von 0°",
        sensors = "SENSOREN", calibrateSensors = "Sensoren kalibrieren",
        calibrationTitle = "Kalibrierung", howToCalibrate = "WIE KALIBRIEREN",
        instrStep1 = "Lege eine Wasserwaage auf eine ebene Fläche.",
        instrStep2 = "Lege das Telefon flach neben die Wasserwaage auf dieselbe Fläche.",
        instrStep3 = "Warte, bis sich die Blase stabilisiert hat.",
        instrStep4 = "Tippe auf 'Kalibrierung starten' — das Telefon speichert die Einstellung.",
        autoCalibration = "AUTOMATISCHE KALIBRIERUNG",
        startCalibration = "Kalibrierung starten", calibrating = "Kalibrierung…",
        calibratedSuccess = "Erfolgreich kalibriert",
        manualCorrection = "MANUELLE KORREKTUR",
        pitchAxisLabel = "Längsachse (Pitch)", rollAxisLabel = "Querachse (Roll)",
        lastCalibration = "Letzte Kalibrierung", resetCalibration = "Kalibrierung zurücksetzen",
        menuTitle = "Menü",
        supportTitle = "Projekt unterstützen",
        supportText = "TrueBubble ist vollständig kostenlos und werbefrei. Wir entwickeln sie mit Begeisterung, damit sie für jeden zugänglich ist.\n\nWenn Sie die App nützlich finden und die Weiterentwicklung unterstützen möchten, besuchen Sie unsere Seite — jede Hilfe, auch symbolisch, ist sehr willkommen.\n\nVielen Dank, dass Sie TrueBubble nutzen!",
        securityTitle = "Sicherheit und Datenschutz",
        securityText = "TrueBubble sammelt keine persönlichen Daten. Alle Daten (Kalibrierung, Einstellungen) werden ausschließlich lokal auf Ihrem Gerät gespeichert und nie an externe Server übertragen.",
        gdprTitle = "DSGVO und Datenschutz",
        gdprText = "Gemäß der DSGVO-Verordnung (EU 2016/679):\n\n• Die App verarbeitet keine personenbezogenen Daten.\n• Es werden keine Cookies oder Tracking verwendet.\n• Kalibrierungsdaten liegen vollständig unter Nutzerkontrolle.\n• Deinstallation der App löscht alle Daten.",
        contactTitle = "Kontakt",
        copiedToClipboard = "In Zwischenablage kopiert",
        compatTitle = "Android-Kompatibilität",
    )

    "fr" -> AppStrings(
        langCode = "fr", poziomica = "Niveau", libella = "Niveau circulaire",
        menuBtn = "Menu", settingsBtn = "Paramètres", closeBtn = "Fermer",
        longitudinal = "LONGITUDINAL", transverse = "TRANSVERSAL",
        remember = "Mémoriser", clear = "Effacer",
        calibrated = "Calibré", notCalibrated = "Non calibré",
        rememberedLine = "Mémorisé",
        settingsTitle = "Paramètres", back = "Retour",
        appearance = "APPARENCE", theme = "Thème", dark = "Sombre", light = "Clair",
        highContrastLabel = "Bulle à contraste élevé",
        highContrastSub = "Améliore la visibilité (opacité plus élevée)",
        bubbleColorLabel = "Couleur de bulle",
        levelSignal = "SIGNAL DE NIVEAU",
        soundOnLevel = "Son au niveau", soundOnLevelSub = "Signal quand 0° est atteint",
        vibrateOnLevel = "Vibration au niveau", vibrateOnLevelSub = "Vibration quand 0° est atteint",
        sensors = "CAPTEURS", calibrateSensors = "Calibrer les capteurs",
        calibrationTitle = "Calibration", howToCalibrate = "COMMENT CALIBRER",
        instrStep1 = "Posez un niveau à bulle sur une surface plane.",
        instrStep2 = "Posez le téléphone à plat à côté du niveau sur la même surface.",
        instrStep3 = "Attendez que la bulle du niveau se stabilise.",
        instrStep4 = "Appuyez sur 'Démarrer la calibration' — le téléphone mémorisera ce réglage.",
        autoCalibration = "CALIBRATION AUTOMATIQUE",
        startCalibration = "Démarrer la calibration", calibrating = "Calibration…",
        calibratedSuccess = "Calibré avec succès",
        manualCorrection = "CORRECTION MANUELLE",
        pitchAxisLabel = "Axe longitudinal (Pitch)", rollAxisLabel = "Axe transversal (Roll)",
        lastCalibration = "Dernière calibration", resetCalibration = "Réinitialiser calibration",
        menuTitle = "Menu",
        supportTitle = "Soutenir le projet",
        supportText = "TrueBubble est entièrement gratuite et sans publicité. Nous la développons avec passion pour qu'elle soit accessible à tous.\n\nSi vous la trouvez utile et souhaitez soutenir le développement, visitez notre page — toute aide, même symbolique, est grandement appréciée.\n\nMerci d'utiliser TrueBubble !",
        securityTitle = "Sécurité et confidentialité",
        securityText = "TrueBubble ne collecte aucune donnée personnelle. Toutes les données (calibration, paramètres) sont stockées uniquement en local sur votre appareil et ne sont jamais envoyées à des serveurs externes.",
        gdprTitle = "RGPD et confidentialité",
        gdprText = "Conformément au Règlement RGPD (EU 2016/679) :\n\n• L'app ne traite aucune donnée personnelle.\n• Aucun cookie ni suivi n'est utilisé.\n• Les données de calibration sont entièrement sous contrôle de l'utilisateur.\n• La désinstallation supprime toutes les données.",
        contactTitle = "Contact",
        copiedToClipboard = "Copié dans le presse-papiers",
        compatTitle = "Compatibilité Android",
    )

    "pt" -> AppStrings(
        langCode = "pt", poziomica = "Nível", libella = "Nível circular",
        menuBtn = "Menu", settingsBtn = "Configurações", closeBtn = "Fechar",
        longitudinal = "LONGITUDINAL", transverse = "TRANSVERSAL",
        remember = "Memorizar", clear = "Limpar",
        calibrated = "Calibrado", notCalibrated = "Não calibrado",
        rememberedLine = "Memorizado",
        settingsTitle = "Configurações", back = "Voltar",
        appearance = "APARÊNCIA", theme = "Tema", dark = "Escuro", light = "Claro",
        highContrastLabel = "Bolha de alto contraste",
        highContrastSub = "Melhora a visibilidade (maior opacidade)",
        bubbleColorLabel = "Cor da bolha",
        levelSignal = "SINAL DE NÍVEL",
        soundOnLevel = "Som no nível", soundOnLevelSub = "Sinal ao atingir 0°",
        vibrateOnLevel = "Vibração no nível", vibrateOnLevelSub = "Vibração ao atingir 0°",
        sensors = "SENSORES", calibrateSensors = "Calibrar sensores",
        calibrationTitle = "Calibração", howToCalibrate = "COMO CALIBRAR",
        instrStep1 = "Coloque um nível de bolha em uma superfície plana.",
        instrStep2 = "Coloque o telefone plano ao lado do nível na mesma superfície.",
        instrStep3 = "Aguarde a bolha do nível se estabilizar.",
        instrStep4 = "Toque em 'Iniciar calibração' — o telefone salvará esta configuração.",
        autoCalibration = "CALIBRAÇÃO AUTOMÁTICA",
        startCalibration = "Iniciar calibração", calibrating = "Calibrando…",
        calibratedSuccess = "Calibrado com sucesso",
        manualCorrection = "CORREÇÃO MANUAL",
        pitchAxisLabel = "Eixo longitudinal (Pitch)", rollAxisLabel = "Eixo transversal (Roll)",
        lastCalibration = "Última calibração", resetCalibration = "Redefinir calibração",
        menuTitle = "Menu",
        supportTitle = "Apoiar o projeto",
        supportText = "TrueBubble é completamente gratuita e sem anúncios. A desenvolvemos com paixão para que esteja disponível para todos.\n\nSe você a achar útil e quiser apoiar o desenvolvimento, visite nossa página — qualquer ajuda, mesmo simbólica, é muito apreciada.\n\nObrigado por usar TrueBubble!",
        securityTitle = "Segurança e privacidade",
        securityText = "TrueBubble não coleta dados pessoais. Todos os dados (calibração, configurações) são armazenados apenas localmente no seu dispositivo e nunca são enviados a servidores externos.",
        gdprTitle = "LGPD e confidencialidade",
        gdprText = "De acordo com as normas de privacidade:\n\n• O app não processa dados pessoais.\n• Nenhum cookie ou rastreamento é utilizado.\n• Os dados de calibração estão sob controle do usuário.\n• Desinstalar o app remove todos os dados.",
        contactTitle = "Contato",
        copiedToClipboard = "Copiado para a área de transferência",
        compatTitle = "Compatibilidade Android",
    )

    "ar" -> AppStrings(
        langCode = "ar", poziomica = "ميزان", libella = "ميزان دائري",
        menuBtn = "القائمة", settingsBtn = "الإعدادات", closeBtn = "إغلاق",
        longitudinal = "طولي", transverse = "عرضي",
        remember = "تذكر", clear = "مسح",
        calibrated = "معايَر", notCalibrated = "غير معايَر",
        rememberedLine = "محفوظ",
        settingsTitle = "الإعدادات", back = "رجوع",
        appearance = "المظهر", theme = "السمة", dark = "داكن", light = "فاتح",
        highContrastLabel = "فقاعة عالية التباين",
        highContrastSub = "يحسّن الرؤية (تعتيم أعلى)",
        bubbleColorLabel = "لون الفقاعة",
        levelSignal = "إشارة المستوى",
        soundOnLevel = "صوت عند المستوى", soundOnLevelSub = "إشارة عند 0°",
        vibrateOnLevel = "اهتزاز عند المستوى", vibrateOnLevelSub = "اهتزاز عند 0°",
        sensors = "أجهزة الاستشعار", calibrateSensors = "معايرة المستشعرات",
        calibrationTitle = "المعايرة", howToCalibrate = "كيفية المعايرة",
        instrStep1 = "ضع ميزان الفقاعة على سطح مستوٍ.",
        instrStep2 = "ضع الهاتف بشكل مسطح بجانب الميزان على نفس السطح.",
        instrStep3 = "انتظر حتى تستقر فقاعة الميزان.",
        instrStep4 = "اضغط على 'بدء المعايرة' — سيحفظ الهاتف هذا الإعداد.",
        autoCalibration = "معايرة تلقائية",
        startCalibration = "بدء المعايرة", calibrating = "جارٍ المعايرة…",
        calibratedSuccess = "تمت المعايرة بنجاح",
        manualCorrection = "تصحيح يدوي",
        pitchAxisLabel = "المحور الطولي (Pitch)", rollAxisLabel = "المحور العرضي (Roll)",
        lastCalibration = "آخر معايرة", resetCalibration = "إعادة ضبط المعايرة",
        menuTitle = "القائمة",
        supportTitle = "دعم المشروع",
        supportText = "TrueBubble مجانية تمامًا وخالية من الإعلانات. نطوّرها بشغف لتكون متاحة للجميع.\n\nإذا وجدتها مفيدة وأردت دعم تطويرها، يرجى زيارة صفحتنا — أي دعم، حتى رمزي، يُقدَّر جدًا ويحفّزنا على الاستمرار.\n\nشكرًا على استخدام TrueBubble!",
        securityTitle = "الأمان والخصوصية",
        securityText = "لا تجمع TrueBubble أي بيانات شخصية. جميع البيانات (المعايرة، الإعدادات) تُخزَّن محليًا فقط على جهازك ولا تُرسَل إلى أي خوادم خارجية.",
        gdprTitle = "خصوصية البيانات",
        gdprText = "وفقًا للوائح الخصوصية:\n\n• التطبيق لا يعالج بيانات شخصية.\n• لا تُستخدم ملفات تعريف الارتباط أو التتبع.\n• بيانات المعايرة تحت سيطرة المستخدم بالكامل.\n• إلغاء التثبيت يحذف جميع البيانات.",
        contactTitle = "التواصل",
        copiedToClipboard = "تم النسخ إلى الحافظة",
        compatTitle = "توافق Android",
    )

    "ru" -> AppStrings(
        langCode = "ru", poziomica = "Уровень", libella = "Пузырьковый",
        menuBtn = "Меню", settingsBtn = "Настройки", closeBtn = "Закрыть",
        longitudinal = "ПРОДОЛЬНО", transverse = "ПОПЕРЕЧНО",
        remember = "Запомнить", clear = "Сброс",
        calibrated = "Откалибровано", notCalibrated = "Не откалибровано",
        rememberedLine = "Запомнено",
        settingsTitle = "Настройки", back = "Назад",
        appearance = "ВНЕШНИЙ ВИД", theme = "Тема", dark = "Тёмная", light = "Светлая",
        highContrastLabel = "Высокий контраст",
        highContrastSub = "Улучшает видимость (выше непрозрачность)",
        bubbleColorLabel = "Цвет пузырька",
        levelSignal = "СИГНАЛ УРОВНЯ",
        soundOnLevel = "Звук при уровне", soundOnLevelSub = "Сигнал при достижении 0°",
        vibrateOnLevel = "Вибрация при уровне", vibrateOnLevelSub = "Вибрация при достижении 0°",
        sensors = "ДАТЧИКИ", calibrateSensors = "Калибровать датчики",
        calibrationTitle = "Калибровка", howToCalibrate = "КАК КАЛИБРОВАТЬ",
        instrStep1 = "Положите уровень на плоскую поверхность.",
        instrStep2 = "Положите телефон плашмя рядом с уровнем на ту же поверхность.",
        instrStep3 = "Подождите, пока пузырёк не стабилизируется.",
        instrStep4 = "Нажмите 'Начать калибровку' — телефон запомнит эту настройку.",
        autoCalibration = "АВТОМАТИЧЕСКАЯ КАЛИБРОВКА",
        startCalibration = "Начать калибровку", calibrating = "Калибровка…",
        calibratedSuccess = "Успешно откалибровано",
        manualCorrection = "РУЧНАЯ КОРРЕКЦИЯ",
        pitchAxisLabel = "Продольная ось (Pitch)", rollAxisLabel = "Поперечная ось (Roll)",
        lastCalibration = "Последняя калибровка", resetCalibration = "Сбросить калибровку",
        menuTitle = "Меню",
        supportTitle = "Поддержать проект",
        supportText = "TrueBubble полностью бесплатна и не содержит рекламы. Мы разрабатываем её с энтузиазмом, чтобы она была доступна каждому.\n\nЕсли приложение оказалось полезным и вы хотите поддержать его развитие, посетите нашу страницу — любая помощь, даже символическая, очень ценится и мотивирует нас продолжать.\n\nСпасибо за использование TrueBubble!",
        securityTitle = "Безопасность и конфиденциальность",
        securityText = "TrueBubble не собирает личные данные. Все данные (калибровка, настройки) хранятся исключительно локально на устройстве и никогда не отправляются на внешние серверы.",
        gdprTitle = "Конфиденциальность данных",
        gdprText = "В соответствии с требованиями по защите данных:\n\n• Приложение не обрабатывает личные данные.\n• Куки и отслеживание не используются.\n• Данные калибровки полностью под контролем пользователя.\n• Удаление приложения удаляет все данные.",
        contactTitle = "Контакт",
        copiedToClipboard = "Скопировано в буфер обмена",
        compatTitle = "Совместимость с Android",
    )

    "id" -> AppStrings(
        langCode = "id", poziomica = "Waterpass", libella = "Waterpass Lingkaran",
        menuBtn = "Menu", settingsBtn = "Pengaturan", closeBtn = "Tutup",
        longitudinal = "MEMBUJUR", transverse = "MELINTANG",
        remember = "Ingat", clear = "Hapus",
        calibrated = "Terkalibrasi", notCalibrated = "Belum dikalibrasi",
        rememberedLine = "Tersimpan",
        settingsTitle = "Pengaturan", back = "Kembali",
        appearance = "TAMPILAN", theme = "Tema", dark = "Gelap", light = "Terang",
        highContrastLabel = "Gelembung kontras tinggi",
        highContrastSub = "Meningkatkan visibilitas (opasitas lebih tinggi)",
        bubbleColorLabel = "Warna gelembung",
        levelSignal = "SINYAL LEVEL",
        soundOnLevel = "Suara saat level", soundOnLevelSub = "Sinyal saat mencapai 0°",
        vibrateOnLevel = "Getar saat level", vibrateOnLevelSub = "Getaran saat mencapai 0°",
        sensors = "SENSOR", calibrateSensors = "Kalibrasi sensor",
        calibrationTitle = "Kalibrasi", howToCalibrate = "CARA KALIBRASI",
        instrStep1 = "Letakkan waterpass di permukaan yang datar.",
        instrStep2 = "Letakkan ponsel datar di samping waterpass pada permukaan yang sama.",
        instrStep3 = "Tunggu hingga gelembung waterpass stabil.",
        instrStep4 = "Ketuk 'Mulai kalibrasi' — ponsel akan menyimpan pengaturan ini.",
        autoCalibration = "KALIBRASI OTOMATIS",
        startCalibration = "Mulai kalibrasi", calibrating = "Mengkalibrasi…",
        calibratedSuccess = "Berhasil dikalibrasi",
        manualCorrection = "KOREKSI MANUAL",
        pitchAxisLabel = "Sumbu membujur (Pitch)", rollAxisLabel = "Sumbu melintang (Roll)",
        lastCalibration = "Kalibrasi terakhir", resetCalibration = "Atur ulang kalibrasi",
        menuTitle = "Menu",
        supportTitle = "Dukung proyek",
        supportText = "TrueBubble sepenuhnya gratis dan bebas iklan. Kami mengembangkannya dengan penuh semangat agar dapat diakses oleh semua orang.\n\nJika aplikasi ini bermanfaat dan Anda ingin mendukung pengembangannya, kunjungi halaman kami — bantuan apa pun, meski simbolis, sangat kami hargai.\n\nTerima kasih telah menggunakan TrueBubble!",
        securityTitle = "Keamanan dan privasi",
        securityText = "TrueBubble tidak mengumpulkan data pribadi. Semua data (kalibrasi, pengaturan) disimpan hanya secara lokal di perangkat Anda dan tidak pernah dikirim ke server eksternal.",
        gdprTitle = "Privasi data",
        gdprText = "Sesuai dengan peraturan privasi:\n\n• Aplikasi tidak memproses data pribadi.\n• Tidak ada cookie atau pelacakan yang digunakan.\n• Data kalibrasi sepenuhnya di bawah kendali pengguna.\n• Menghapus instalasi aplikasi menghapus semua data.",
        contactTitle = "Kontak",
        copiedToClipboard = "Disalin ke papan klip",
        compatTitle = "Kompatibilitas Android",
    )

    "ja" -> AppStrings(
        langCode = "ja", poziomica = "水準器", libella = "円形水準器",
        menuBtn = "メニュー", settingsBtn = "設定", closeBtn = "閉じる",
        longitudinal = "縦方向", transverse = "横方向",
        remember = "記憶", clear = "クリア",
        calibrated = "調整済み", notCalibrated = "未調整",
        rememberedLine = "記憶済み",
        settingsTitle = "設定", back = "戻る",
        appearance = "外観", theme = "テーマ", dark = "ダーク", light = "ライト",
        highContrastLabel = "高コントラスト気泡",
        highContrastSub = "視認性向上（不透明度増加）",
        bubbleColorLabel = "気泡の色",
        levelSignal = "水準シグナル",
        soundOnLevel = "水準時の音", soundOnLevelSub = "0°達成時にシグナル",
        vibrateOnLevel = "水準時の振動", vibrateOnLevelSub = "0°達成時に振動",
        sensors = "センサー", calibrateSensors = "センサー調整",
        calibrationTitle = "調整", howToCalibrate = "調整方法",
        instrStep1 = "水準器を平らな面に置いてください。",
        instrStep2 = "スマートフォンを水準器の横に平らに置いてください。",
        instrStep3 = "水準器の気泡が安定するまで待ちます。",
        instrStep4 = "「調整を開始」をタップ — スマートフォンがこの設定を保存します。",
        autoCalibration = "自動調整",
        startCalibration = "調整を開始", calibrating = "調整中…",
        calibratedSuccess = "調整完了",
        manualCorrection = "手動補正",
        pitchAxisLabel = "縦軸 (Pitch)", rollAxisLabel = "横軸 (Roll)",
        lastCalibration = "最終調整", resetCalibration = "調整をリセット",
        menuTitle = "メニュー",
        supportTitle = "プロジェクトを支援",
        supportText = "TrueBubbleは完全無料で広告なしのアプリです。誰もが使えるよう、情熱を持って開発しています。\n\n役に立った場合は、ぜひ私たちのページをご覧いただき、プロジェクトへのご支援をご検討ください。どんなサポートも大変ありがたく、開発の励みになります。\n\nTrueBubbleをご利用いただきありがとうございます！",
        securityTitle = "セキュリティとプライバシー",
        securityText = "TrueBubbleは個人データを収集しません。すべてのデータ（調整、設定）はデバイスにのみローカルに保存され、外部サーバーに送信されることはありません。",
        gdprTitle = "データプライバシー",
        gdprText = "プライバシー規則に従い：\n\n• アプリは個人データを処理しません。\n• クッキーやトラッキングは使用しません。\n• 調整データはユーザーが完全に管理します。\n• アプリをアンインストールすると全データが削除されます。",
        contactTitle = "お問い合わせ",
        copiedToClipboard = "クリップボードにコピーしました",
        compatTitle = "Android互換性",
    )

    else -> AppStrings(  // "en" default
        langCode = "en", poziomica = "Level", libella = "Bullseye",
        menuBtn = "Menu", settingsBtn = "Settings", closeBtn = "Close",
        longitudinal = "LONGITUDINAL", transverse = "TRANSVERSE",
        remember = "Remember", clear = "Clear",
        calibrated = "Calibrated", notCalibrated = "Not calibrated",
        rememberedLine = "Remembered",
        settingsTitle = "Settings", back = "Back",
        appearance = "APPEARANCE", theme = "Theme", dark = "Dark", light = "Light",
        highContrastLabel = "High contrast bubble",
        highContrastSub = "Improves visibility (higher opacity)",
        bubbleColorLabel = "Bubble color",
        levelSignal = "LEVEL SIGNAL",
        soundOnLevel = "Sound at level", soundOnLevelSub = "Signal when 0° is reached",
        vibrateOnLevel = "Vibration at level", vibrateOnLevelSub = "Vibration when 0° is reached",
        sensors = "SENSORS", calibrateSensors = "Calibrate sensors",
        calibrationTitle = "Calibration", howToCalibrate = "HOW TO CALIBRATE",
        instrStep1 = "Place a spirit level on a flat surface.",
        instrStep2 = "Lay your phone flat next to the spirit level on the same surface.",
        instrStep3 = "Wait for the spirit level bubble to stabilize.",
        instrStep4 = "Tap 'Start calibration' — the phone will save this setting.",
        autoCalibration = "AUTO CALIBRATION",
        startCalibration = "Start calibration", calibrating = "Calibrating…",
        calibratedSuccess = "Calibrated successfully",
        manualCorrection = "MANUAL CORRECTION",
        pitchAxisLabel = "Longitudinal axis (Pitch)", rollAxisLabel = "Transverse axis (Roll)",
        lastCalibration = "Last calibration", resetCalibration = "Reset calibration",
        menuTitle = "Menu",
        supportTitle = "Support the project",
        supportText = "TrueBubble is completely free and ad-free. We develop it with passion to make it available to everyone.\n\nIf you find it useful and would like to support its development, please visit our page — any help, even symbolic, is greatly appreciated and motivates us to keep improving.\n\nThank you for using TrueBubble!",
        securityTitle = "Security & Privacy",
        securityText = "TrueBubble does not collect any personal data. All data (calibration, settings) is stored locally on your device only and is never sent to any external servers.",
        gdprTitle = "GDPR & Data Privacy",
        gdprText = "In accordance with privacy regulations (GDPR EU 2016/679):\n\n• The app does not process personal data.\n• No cookies or tracking are used.\n• Calibration data is entirely under user control.\n• Uninstalling the app deletes all data.",
        contactTitle = "Contact",
        copiedToClipboard = "Copied to clipboard",
        compatTitle = "Android Compatibility",
    )
}
