package com.truebubble.ui.strings

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    val langCode: String,
    val poziomica: String,
    val libella: String,
    val menuBtn: String,
    val settingsBtn: String,
    val closeBtn: String,
    val longitudinal: String,
    val transverse: String,
    val remember: String,
    val clear: String,
    val calibrated: String,
    val notCalibrated: String,
    val rememberedLine: String,
    val longitudinalShort: String,
    val transverseShort: String,
    val settingsTitle: String,
    val back: String,
    val appearance: String,
    val theme: String,
    val dark: String,
    val light: String,
    val highContrastLabel: String,
    val highContrastSub: String,
    val bubbleColorLabel: String,
    val levelSignal: String,
    val soundOnLevel: String,
    val soundOnLevelSub: String,
    val vibrateOnLevel: String,
    val vibrateOnLevelSub: String,
    val sensors: String,
    val calibrateSensors: String,
    val calibrationTitle: String,
    val howToCalibrate: String,
    val instrStep1: String,
    val instrStep2: String,
    val instrStep3: String,
    val instrStep4: String,
    val autoCalibration: String,
    val startCalibration: String,
    val calibrating: String,
    val calibratedSuccess: String,
    val manualCorrection: String,
    val manualCorrectionSub: String,
    val calibrationData: String,
    val pitchAxisLabel: String,
    val rollAxisLabel: String,
    val lastCalibration: String,
    val resetCalibration: String,
    val menuTitle: String,
    val supportTitle: String,
    val supportText: String,
    val securityTitle: String,
    val securityText: String,
    val gdprTitle: String,
    val gdprText: String,
    val contactTitle: String,
    val copiedToClipboard: String,
    val compatTitle: String,
    val versionLabel: String,
    val rateApp: String,
    val termsTitle: String,
    val termsBody: String,
    val contactBody: String,
    val contactLinkLabel: String,
    val privacyLinkLabel: String,
)

val LocalAppStrings = compositionLocalOf { stringsFor("en") }

data class LangItem(val code: String, val flag: String, val name: String)

val supportedLanguages = listOf(
    LangItem("pl", "🇵🇱", "Polski"),
    LangItem("en", "🇬🇧", "English"),
    LangItem("es", "🇪🇸", "Español"),
    LangItem("de", "🇩🇪", "Deutsch"),
    LangItem("fr", "🇫🇷", "Français"),
    LangItem("pt", "🇧🇷", "Português (BR)"),
    LangItem("ar", "🇸🇦", "العربية"),
    LangItem("ru", "🇷🇺", "Русский"),
    LangItem("id", "🇮🇩", "Bahasa Indonesia"),
    LangItem("ja", "🇯🇵", "日本語"),
)

fun flagFor(code: String): String = supportedLanguages.find { it.code == code }?.flag ?: "🌐"

@Suppress("LongMethod")
fun stringsFor(code: String): AppStrings = when (code) {

    "pl" -> AppStrings(
        langCode = "pl",
        poziomica = "Poziomica",
        libella = "Libella",
        menuBtn = "Menu",
        settingsBtn = "Ustawienia",
        closeBtn = "Zamknij",
        longitudinal = "WZDŁUŻNIE",
        transverse = "POPRZECZNIE",
        remember = "Zapamiętaj",
        clear = "Wyczyść",
        calibrated = "Skalibrowano",
        notCalibrated = "Nieskalibrowano",
        rememberedLine = "Zapamiętano",
        longitudinalShort = "Wzdł.",
        transverseShort = "Poprz.",
        settingsTitle = "Ustawienia",
        back = "Wstecz",
        appearance = "WYGLĄD",
        theme = "Motyw",
        dark = "Ciemny",
        light = "Jasny",
        highContrastLabel = "Duży kontrast łezki",
        highContrastSub = "Zwiększa widoczność (większa przezroczystość)",
        bubbleColorLabel = "Kolor łezki",
        levelSignal = "SYGNAŁ POZIOMU",
        soundOnLevel = "Dźwięk przy poziomie",
        soundOnLevelSub = "Sygnał przy osiągnięciu 0°",
        vibrateOnLevel = "Wibracja przy poziomie",
        vibrateOnLevelSub = "Wibracja przy osiągnięciu 0°",
        sensors = "CZUJNIKI",
        calibrateSensors = "Kalibracja czujników",
        calibrationTitle = "Kalibracja",
        howToCalibrate = "JAK KALIBROWAĆ",
        instrStep1 = "Połóż klasyczną poziomnicę na płaskiej powierzchni.",
        instrStep2 = "Połóż telefon na poziomicy.",
        instrStep3 = "Poczekaj aż bąbelek poziomicy się ustabilizuje.",
        instrStep4 = "Naciśnij 'Rozpocznij kalibrację' - telefon zapamięta to ustawienie.",
        autoCalibration = "KALIBRACJA AUTOMATYCZNA",
        startCalibration = "Rozpocznij auto kalibrację",
        calibrating = "Kalibrowanie…",
        calibratedSuccess = "Skalibrowano pomyślnie",
        manualCorrection = "RĘCZNA KALIBRACJA",
        manualCorrectionSub = "Przyłóż telefon płasko do tradycyjnej poziomicy i ręcznie skoryguj wartość Pitch i Roll.",
        calibrationData = "DANE KALIBRACJI",
        pitchAxisLabel = "Oś wzdłużna (Pitch)",
        rollAxisLabel = "Oś poprzeczna (Roll)",
        lastCalibration = "Ostatnia kalibracja",
        resetCalibration = "Resetuj kalibrację",
        menuTitle = "Menu",
        supportTitle = "Wsparcie projektu",
        supportText = "TrueBubble jest w pełni darmową aplikacją, wolną od reklam i ukrytych opłat. Tworzymy ją z pasji i chcemy, żeby była dostępna dla każdego.\nJeśli aplikacja okazała się dla Ciebie przydatna i chciałbyś wesprzec dalszy rozwój projektu, odwiedź naszą stronę - każde wsparcie, nawet symboliczne, pozwala nam rozwijać TrueBubble.\nDziękujemy za korzystanie z TrueBubble!",
        securityTitle = "Polityka prywatności",
        securityText = "Aplikacja TrueBubble nie zbiera żadnych danych osobowych. Wszystkie dane (kalibracja, ustawienia) są przechowywane wyłącznie lokalnie na urządzeniu i nie są wysyłane na żadne serwery zewnętrzne.",
        gdprTitle = "RODO i poufność danych",
        gdprText = "Zgodnie z Rozporządzeniem RODO (EU 2016/679):\n- Aplikacja nie przetwarza danych osobowych.\n- Nie są stosowane pliki cookies ani śledzenie.\n- Dane kalibracji i ustawień są w pełni pod kontrolą użytkownika.\n- Odinstalowanie aplikacji usuwa wszystkie dane.",
        contactTitle = "Kontakt / Zgłoś błąd / Propozycja zmian",
        copiedToClipboard = "Skopiowano do schowka",
        compatTitle = "Zgodność z Android",
        versionLabel = "Wersja",
        rateApp = "Oceń aplikację",
        termsTitle = "Regulamin",
        termsBody = "Korzystając z TrueBubble akceptujesz poniższe zasady: aplikacja pełni funkcję pomocniczego narzędzia pomiarowego (cyfrowa poziomica) i nie zastępuje profesjonalnych przyrządów pomiarowych w zastosowaniach wymagających wysokiej precyzji. Jesteś w pełni odpowiedzialny/a za sposób wykorzystania wyników pomiarów. Aplikacja dostarczana jest w stanie „tak jak jest\", bez gwarancji nieprzerwanego działania czy braku błędów. Autor nie ponosi odpowiedzialności za szkody wynikające z niedokładności pomiarów lub błędnego użycia aplikacji.",
        contactBody = "Coś nie działa? Masz pomysł na nową funkcję? A może po prostu chcesz się przywitać? Wypełnij krótki formularz - każdą wiadomość czytamy osobiście.",
        contactLinkLabel = "Otwórz formularz",
        privacyLinkLabel = "Zobacz pełną politykę prywatności",
    )

    "es" -> AppStrings(
        langCode = "es",
        poziomica = "Nivel",
        libella = "Nivel circular",
        menuBtn = "Menú",
        settingsBtn = "Ajustes",
        closeBtn = "Cerrar",
        longitudinal = "LONGITUDINAL",
        transverse = "TRANSVERSAL",
        remember = "Recordar",
        clear = "Borrar",
        calibrated = "Calibrado",
        notCalibrated = "Sin calibrar",
        rememberedLine = "Recordado",
        longitudinalShort = "Long.",
        transverseShort = "Trans.",
        settingsTitle = "Ajustes",
        back = "Atrás",
        appearance = "APARIENCIA",
        theme = "Tema",
        dark = "Oscuro",
        light = "Claro",
        highContrastLabel = "Burbuja alto contraste",
        highContrastSub = "Mejora la visibilidad (mayor opacidad)",
        bubbleColorLabel = "Color de burbuja",
        levelSignal = "SEÑAL DE NIVEL",
        soundOnLevel = "Sonido al nivelar",
        soundOnLevelSub = "Señal al alcanzar 0°",
        vibrateOnLevel = "Vibración al nivelar",
        vibrateOnLevelSub = "Vibración al alcanzar 0°",
        sensors = "SENSORES",
        calibrateSensors = "Calibrar sensores",
        calibrationTitle = "Calibración",
        howToCalibrate = "CÓMO CALIBRAR",
        instrStep1 = "Coloca un nivel de burbuja en una superficie plana.",
        instrStep2 = "Pon el teléfono sobre el nivel.",
        instrStep3 = "Espera a que la burbuja del nivel se estabilice.",
        instrStep4 = "Toca 'Iniciar calibración' - el teléfono guardará este ajuste.",
        autoCalibration = "CALIBRACIÓN AUTOMÁTICA",
        startCalibration = "Iniciar auto calibración",
        calibrating = "Calibrando…",
        calibratedSuccess = "Calibrado con éxito",
        manualCorrection = "CALIBRACIÓN MANUAL",
        manualCorrectionSub = "Coloca el teléfono plano sobre un nivel de burbuja tradicional y ajusta manualmente los valores de Pitch y Roll.",
        calibrationData = "DATOS DE CALIBRACIÓN",
        pitchAxisLabel = "Eje longitudinal (Pitch)",
        rollAxisLabel = "Eje transversal (Roll)",
        lastCalibration = "Última calibración",
        resetCalibration = "Restablecer calibración",
        menuTitle = "Menú",
        supportTitle = "Apoyar el proyecto",
        supportText = "TrueBubble es completamente gratuita y sin anuncios. La creamos con pasión para que esté disponible para todos.\nSi la encuentras útil y deseas apoyar el desarrollo, visita nuestra página - cualquier apoyo, incluso simbólico, nos ayuda a mejorar TrueBubble.\n¡Gracias por usar TrueBubble!",
        securityTitle = "Política de privacidad",
        securityText = "TrueBubble no recopila datos personales. Todos los datos (calibración, ajustes) se almacenan únicamente de forma local en tu dispositivo y nunca se envían a servidores externos.",
        gdprTitle = "RGPD y confidencialidad",
        gdprText = "De acuerdo con el Reglamento RGPD (EU 2016/679):\n- La app no procesa datos personales.\n- No se usan cookies ni seguimiento.\n- Los datos de calibración están bajo el control del usuario.\n- Desinstalar la app elimina todos los datos.",
        contactTitle = "Contacto / Reportar error / Solicitar función",
        copiedToClipboard = "Copiado al portapapeles",
        compatTitle = "Compatibilidad con Android",
        versionLabel = "Versión",
        rateApp = "Valorar la app",
        termsTitle = "Términos de servicio",
        termsBody = "Al usar TrueBubble aceptas lo siguiente: la aplicación funciona como herramienta de medición auxiliar (nivel de burbuja digital) y no sustituye a instrumentos de medición profesionales en aplicaciones que requieran alta precisión. Eres el único responsable del uso que hagas de los resultados de medición. La aplicación se proporciona \"tal cual\", sin garantía de funcionamiento ininterrumpido o libre de errores. El desarrollador no se hace responsable de los daños derivados de la imprecisión de las mediciones o del mal uso de la aplicación.",
        contactBody = "¿Encontraste un error o tienes una idea para una nueva función? ¿Solo quieres saludar? Completa un formulario breve - cada mensaje se lee personalmente.",
        contactLinkLabel = "Abrir formulario",
        privacyLinkLabel = "Ver política de privacidad completa",
    )

    "de" -> AppStrings(
        langCode = "de",
        poziomica = "Wasserwaage",
        libella = "Libelle",
        menuBtn = "Menü",
        settingsBtn = "Einstellungen",
        closeBtn = "Schließen",
        longitudinal = "LÄNGSNEIGUNG",
        transverse = "QUERNEIGUNG",
        remember = "Merken",
        clear = "Löschen",
        calibrated = "Kalibriert",
        notCalibrated = "Nicht kalibriert",
        rememberedLine = "Gemerkt",
        longitudinalShort = "Längs.",
        transverseShort = "Quer.",
        settingsTitle = "Einstellungen",
        back = "Zurück",
        appearance = "AUSSEHEN",
        theme = "Thema",
        dark = "Dunkel",
        light = "Hell",
        highContrastLabel = "Hoher Kontrast Blase",
        highContrastSub = "Verbessert Sichtbarkeit (höhere Opazität)",
        bubbleColorLabel = "Blasenfarbe",
        levelSignal = "NIVEAU-SIGNAL",
        soundOnLevel = "Ton bei Niveau",
        soundOnLevelSub = "Signal bei Erreichen von 0°",
        vibrateOnLevel = "Vibration bei Niveau",
        vibrateOnLevelSub = "Vibration bei Erreichen von 0°",
        sensors = "SENSOREN",
        calibrateSensors = "Sensoren kalibrieren",
        calibrationTitle = "Kalibrierung",
        howToCalibrate = "WIE KALIBRIEREN",
        instrStep1 = "Lege eine Wasserwaage auf eine ebene Fläche.",
        instrStep2 = "Lege das Telefon flach auf die Wasserwaage.",
        instrStep3 = "Warte, bis sich die Blase stabilisiert hat.",
        instrStep4 = "Tippe auf 'Kalibrierung starten' - das Telefon speichert die Einstellung.",
        autoCalibration = "AUTOMATISCHE KALIBRIERUNG",
        startCalibration = "Auto-Kalibrierung starten",
        calibrating = "Kalibrierung…",
        calibratedSuccess = "Erfolgreich kalibriert",
        manualCorrection = "MANUELLE KALIBRIERUNG",
        manualCorrectionSub = "Legen Sie das Telefon flach auf eine traditionelle Wasserwaage und korrigieren Sie manuell Pitch und Roll.",
        calibrationData = "KALIBRIERDATEN",
        pitchAxisLabel = "Längsachse (Pitch)",
        rollAxisLabel = "Querachse (Roll)",
        lastCalibration = "Letzte Kalibrierung",
        resetCalibration = "Kalibrierung zurücksetzen",
        menuTitle = "Menü",
        supportTitle = "Projekt unterstützen",
        supportText = "TrueBubble ist vollständig kostenlos und werbefrei. Wir entwickeln sie mit Begeisterung, damit sie für jeden zugänglich ist.\nWenn Sie die App nützlich finden und die Weiterentwicklung unterstützen möchten, besuchen Sie unsere Seite - jede Hilfe, auch symbolisch, ist sehr willkommen.\nVielen Dank, dass Sie TrueBubble nutzen!",
        securityTitle = "Datenschutzerklärung",
        securityText = "TrueBubble sammelt keine persönlichen Daten. Alle Daten (Kalibrierung, Einstellungen) werden ausschließlich lokal auf Ihrem Gerät gespeichert und nie an externe Server übertragen.",
        gdprTitle = "DSGVO und Datenschutz",
        gdprText = "Gemäß der DSGVO-Verordnung (EU 2016/679):\n- Die App verarbeitet keine personenbezogenen Daten.\n- Es werden keine Cookies oder Tracking verwendet.\n- Kalibrierungsdaten liegen vollständig unter Nutzerkontrolle.\n- Deinstallation der App löscht alle Daten.",
        contactTitle = "Kontakt / Fehler melden / Funktionswunsch",
        copiedToClipboard = "In Zwischenablage kopiert",
        compatTitle = "Android-Kompatibilität",
        versionLabel = "Version",
        rateApp = "App bewerten",
        termsTitle = "Nutzungsbedingungen",
        termsBody = "Mit der Nutzung von TrueBubble stimmst du Folgendem zu: Die App dient als ergänzendes Messwerkzeug (digitale Wasserwaage) und ersetzt keine professionellen Messgeräte in Anwendungen, die hohe Präzision erfordern. Du bist allein verantwortlich für die Nutzung der Messergebnisse. Die App wird \"wie besehen\" bereitgestellt, ohne Garantie für unterbrechungsfreien oder fehlerfreien Betrieb. Der Entwickler haftet nicht für Schäden, die durch Messungenauigkeiten oder falsche Nutzung der App entstehen.",
        contactBody = "Hast du einen Fehler gefunden oder eine Idee für eine neue Funktion? Möchtest du einfach nur Hallo sagen? Fülle das kurze Formular aus - jede Nachricht wird persönlich gelesen.",
        contactLinkLabel = "Formular öffnen",
        privacyLinkLabel = "Vollständige Datenschutzerklärung ansehen",
    )

    "fr" -> AppStrings(
        langCode = "fr",
        poziomica = "Niveau",
        libella = "Niveau circulaire",
        menuBtn = "Menu",
        settingsBtn = "Paramètres",
        closeBtn = "Fermer",
        longitudinal = "LONGITUDINAL",
        transverse = "TRANSVERSAL",
        remember = "Mémoriser",
        clear = "Effacer",
        calibrated = "Calibré",
        notCalibrated = "Non calibré",
        rememberedLine = "Mémorisé",
        longitudinalShort = "Long.",
        transverseShort = "Trans.",
        settingsTitle = "Paramètres",
        back = "Retour",
        appearance = "APPARENCE",
        theme = "Thème",
        dark = "Sombre",
        light = "Clair",
        highContrastLabel = "Bulle à contraste élevé",
        highContrastSub = "Améliore la visibilité (opacité plus élevée)",
        bubbleColorLabel = "Couleur de bulle",
        levelSignal = "SIGNAL DE NIVEAU",
        soundOnLevel = "Son au niveau",
        soundOnLevelSub = "Signal quand 0° est atteint",
        vibrateOnLevel = "Vibration au niveau",
        vibrateOnLevelSub = "Vibration quand 0° est atteint",
        sensors = "CAPTEURS",
        calibrateSensors = "Calibrer les capteurs",
        calibrationTitle = "Calibration",
        howToCalibrate = "COMMENT CALIBRER",
        instrStep1 = "Posez un niveau à bulle sur une surface plane.",
        instrStep2 = "Posez le téléphone sur le niveau.",
        instrStep3 = "Attendez que la bulle du niveau se stabilise.",
        instrStep4 = "Appuyez sur 'Démarrer la calibration' - le téléphone mémorisera ce réglage.",
        autoCalibration = "CALIBRATION AUTOMATIQUE",
        startCalibration = "Démarrer la calibration auto",
        calibrating = "Calibration…",
        calibratedSuccess = "Calibré avec succès",
        manualCorrection = "CALIBRATION MANUELLE",
        manualCorrectionSub = "Posez le téléphone à plat sur un niveau à bulle traditionnel et corrigez manuellement les valeurs Pitch et Roll.",
        calibrationData = "DONNÉES DE CALIBRATION",
        pitchAxisLabel = "Axe longitudinal (Pitch)",
        rollAxisLabel = "Axe transversal (Roll)",
        lastCalibration = "Dernière calibration",
        resetCalibration = "Réinitialiser calibration",
        menuTitle = "Menu",
        supportTitle = "Soutenir le projet",
        supportText = "TrueBubble est entièrement gratuite et sans publicité. Nous la développons avec passion pour qu'elle soit accessible à tous.\nSi vous la trouvez utile et souhaitez soutenir le développement, visitez notre page - toute aide, même symbolique, est grandement appréciée.\nMerci d'utiliser TrueBubble !",
        securityTitle = "Politique de confidentialité",
        securityText = "TrueBubble ne collecte aucune donnée personnelle. Toutes les données (calibration, paramètres) sont stockées uniquement en local sur votre appareil et ne sont jamais envoyées à des serveurs externes.",
        gdprTitle = "RGPD et confidentialité",
        gdprText = "Conformément au Règlement RGPD (EU 2016/679) :\n- L'app ne traite aucune donnée personnelle.\n- Aucun cookie ni suivi n'est utilisé.\n- Les données de calibration sont entièrement sous contrôle de l'utilisateur.\n- La désinstallation supprime toutes les données.",
        contactTitle = "Contact / Signaler un bug / Demande de fonctionnalité",
        copiedToClipboard = "Copié dans le presse-papiers",
        compatTitle = "Compatibilité Android",
        versionLabel = "Version",
        rateApp = "Noter l'application",
        termsTitle = "Conditions d'utilisation",
        termsBody = "En utilisant TrueBubble, vous acceptez les conditions suivantes : l'application sert d'outil de mesure auxiliaire (niveau à bulle numérique) et ne remplace pas les instruments de mesure professionnels pour les applications exigeant une haute précision. Vous êtes seul responsable de l'usage que vous faites des résultats de mesure. L'application est fournie « en l'état », sans garantie de fonctionnement ininterrompu ou sans erreur. Le développeur n'est pas responsable des dommages résultant d'une imprécision de mesure ou d'une mauvaise utilisation de l'application.",
        contactBody = "Vous avez trouvé un bug ou une idée de nouvelle fonctionnalité ? Vous voulez simplement nous dire bonjour ? Remplissez un court formulaire - chaque message est lu personnellement.",
        contactLinkLabel = "Ouvrir le formulaire",
        privacyLinkLabel = "Voir la politique de confidentialité complète",
    )

    "pt" -> AppStrings(
        langCode = "pt",
        poziomica = "Nível",
        libella = "Nível circular",
        menuBtn = "Menu",
        settingsBtn = "Configurações",
        closeBtn = "Fechar",
        longitudinal = "LONGITUDINAL",
        transverse = "TRANSVERSAL",
        remember = "Memorizar",
        clear = "Limpar",
        calibrated = "Calibrado",
        notCalibrated = "Não calibrado",
        rememberedLine = "Memorizado",
        longitudinalShort = "Long.",
        transverseShort = "Trans.",
        settingsTitle = "Configurações",
        back = "Voltar",
        appearance = "APARÊNCIA",
        theme = "Tema",
        dark = "Escuro",
        light = "Claro",
        highContrastLabel = "Bolha de alto contraste",
        highContrastSub = "Melhora a visibilidade (maior opacidade)",
        bubbleColorLabel = "Cor da bolha",
        levelSignal = "SINAL DE NÍVEL",
        soundOnLevel = "Som no nível",
        soundOnLevelSub = "Sinal ao atingir 0°",
        vibrateOnLevel = "Vibração no nível",
        vibrateOnLevelSub = "Vibração ao atingir 0°",
        sensors = "SENSORES",
        calibrateSensors = "Calibrar sensores",
        calibrationTitle = "Calibração",
        howToCalibrate = "COMO CALIBRAR",
        instrStep1 = "Coloque um nível de bolha em uma superfície plana.",
        instrStep2 = "Coloque o telefone sobre o nível.",
        instrStep3 = "Aguarde a bolha do nível se estabilizar.",
        instrStep4 = "Toque em 'Iniciar calibração' - o telefone salvará esta configuração.",
        autoCalibration = "CALIBRAÇÃO AUTOMÁTICA",
        startCalibration = "Iniciar auto calibração",
        calibrating = "Calibrando…",
        calibratedSuccess = "Calibrado com sucesso",
        manualCorrection = "CALIBRAÇÃO MANUAL",
        manualCorrectionSub = "Coloque o telefone plano sobre um nível de bolha tradicional e corrija manualmente os valores de Pitch e Roll.",
        calibrationData = "DADOS DE CALIBRAÇÃO",
        pitchAxisLabel = "Eixo longitudinal (Pitch)",
        rollAxisLabel = "Eixo transversal (Roll)",
        lastCalibration = "Última calibração",
        resetCalibration = "Redefinir calibração",
        menuTitle = "Menu",
        supportTitle = "Apoiar o projeto",
        supportText = "TrueBubble é completamente gratuita e sem anúncios. A desenvolvemos com paixão para que esteja disponível para todos.\nSe você a achar útil e quiser apoiar o desenvolvimento, visite nossa página - qualquer ajuda, mesmo simbólica, é muito apreciada.\nObrigado por usar TrueBubble!",
        securityTitle = "Política de privacidade",
        securityText = "TrueBubble não coleta dados pessoais. Todos os dados (calibração, configurações) são armazenados apenas localmente no seu dispositivo e nunca são enviados a servidores externos.",
        gdprTitle = "LGPD e confidencialidade",
        gdprText = "De acordo com as normas de privacidade:\n- O app não processa dados pessoais.\n- Nenhum cookie ou rastreamento é utilizado.\n- Os dados de calibração estão sob controle do usuário.\n- Desinstalar o app remove todos os dados.",
        contactTitle = "Contato / Reportar bug / Solicitar recurso",
        copiedToClipboard = "Copiado para a área de transferência",
        compatTitle = "Compatibilidade Android",
        versionLabel = "Versão",
        rateApp = "Avaliar o app",
        termsTitle = "Termos de uso",
        termsBody = "Ao usar o TrueBubble, você concorda com o seguinte: o aplicativo funciona como uma ferramenta de medição auxiliar (nível de bolha digital) e não substitui instrumentos de medição profissionais em aplicações que exijam alta precisão. Você é o único responsável pelo uso que fizer dos resultados de medição. O aplicativo é fornecido \"como está\", sem garantia de funcionamento ininterrupto ou livre de erros. O desenvolvedor não se responsabiliza por danos decorrentes de imprecisão de medição ou uso indevido do aplicativo.",
        contactBody = "Encontrou um bug ou tem uma ideia para um novo recurso? Só quer dizer oi? Preencha um formulário curto - cada mensagem é lida pessoalmente.",
        contactLinkLabel = "Abrir formulário",
        privacyLinkLabel = "Ver política de privacidade completa",
    )

    "ar" -> AppStrings(
        langCode = "ar",
        poziomica = "ميزان",
        libella = "ميزان دائري",
        menuBtn = "القائمة",
        settingsBtn = "الإعدادات",
        closeBtn = "إغلاق",
        longitudinal = "طولي",
        transverse = "عرضي",
        remember = "تذكر",
        clear = "مسح",
        calibrated = "معايَر",
        notCalibrated = "غير معايَر",
        rememberedLine = "محفوظ",
        longitudinalShort = "طولي",
        transverseShort = "عرضي",
        settingsTitle = "الإعدادات",
        back = "رجوع",
        appearance = "المظهر",
        theme = "السمة",
        dark = "داكن",
        light = "فاتح",
        highContrastLabel = "فقاعة عالية التباين",
        highContrastSub = "يحسّن الرؤية (تعتيم أعلى)",
        bubbleColorLabel = "لون الفقاعة",
        levelSignal = "إشارة المستوى",
        soundOnLevel = "صوت عند المستوى",
        soundOnLevelSub = "إشارة عند 0°",
        vibrateOnLevel = "اهتزاز عند المستوى",
        vibrateOnLevelSub = "اهتزاز عند 0°",
        sensors = "أجهزة الاستشعار",
        calibrateSensors = "معايرة المستشعرات",
        calibrationTitle = "المعايرة",
        howToCalibrate = "كيفية المعايرة",
        instrStep1 = "ضع ميزان الفقاعة على سطح مستوٍ.",
        instrStep2 = "ضع الهاتف على الميزان.",
        instrStep3 = "انتظر حتى تستقر فقاعة الميزان.",
        instrStep4 = "اضغط على 'بدء المعايرة' - سيحفظ الهاتف هذا الإعداد.",
        autoCalibration = "معايرة تلقائية",
        startCalibration = "بدء المعايرة التلقائية",
        calibrating = "جارٍ المعايرة…",
        calibratedSuccess = "تمت المعايرة بنجاح",
        manualCorrection = "معايرة يدوية",
        manualCorrectionSub = "ضع الهاتف بشكل مستوٍ على ميزان فقاعي تقليدي وقم بتصحيح قيمتَي Pitch وRoll يدوياً.",
        calibrationData = "بيانات المعايرة",
        pitchAxisLabel = "المحور الطولي (Pitch)",
        rollAxisLabel = "المحور العرضي (Roll)",
        lastCalibration = "آخر معايرة",
        resetCalibration = "إعادة ضبط المعايرة",
        menuTitle = "القائمة",
        supportTitle = "دعم المشروع",
        supportText = "TrueBubble مجانية تماماً وخالية من الإعلانات. نطورها بشغف لتكون متاحة للجميع.\nإذا وجدتها مفيدة وأردت دعم تطويرها، يرجى زيارة صفحتنا - أي دعم يُقدّر جداً.\nشكراً على استخدام TrueBubble!",
        securityTitle = "سياسة الخصوصية",
        securityText = "لا تجمع TrueBubble أي بيانات شخصية. جميع البيانات (المعايرة، الإعدادات) تُخزّن محلياً فقط على جهازك ولا تُرسَل إلى أي خوادم خارجية.",
        gdprTitle = "خصوصية البيانات",
        gdprText = "وفقاً للوائح الخصوصية:\n- التطبيق لا يعالج بيانات شخصية.\n- لا تُستخدم ملفات تعريف الارتباط أو التتبع.\n- بيانات المعايرة تحت سيطرة المستخدم بالكامل.\n- إلغاء التثبيت يحذف جميع البيانات.",
        contactTitle = "تواصل / الإبلاغ عن خطأ / طلب ميزة",
        copiedToClipboard = "تم النسخ إلى الحافظة",
        compatTitle = "توافق Android",
        versionLabel = "الإصدار",
        rateApp = "قيّم التطبيق",
        termsTitle = "شروط الخدمة",
        termsBody = "باستخدامك لتطبيق TrueBubble فإنك توافق على ما يلي: يعمل التطبيق كأداة قياس مساعدة (ميزان فقاعي رقمي) ولا يحل محل أدوات القياس الاحترافية في التطبيقات التي تتطلب دقة عالية. أنت المسؤول الوحيد عن كيفية استخدامك لنتائج القياس. يُقدَّم التطبيق \"كما هو\" دون أي ضمان لتشغيل مستمر أو خالٍ من الأخطاء. لا يتحمل المطور أي مسؤولية عن الأضرار الناتجة عن عدم دقة القياس أو سوء استخدام التطبيق.",
        contactBody = "هل وجدت خطأ أم لديك فكرة لميزة جديدة؟ أم تريد فقط إلقاء التحية؟ املأ نموذجًا قصيرًا - تتم قراءة كل رسالة شخصيًا.",
        contactLinkLabel = "افتح النموذج",
        privacyLinkLabel = "عرض سياسة الخصوصية الكاملة",
    )

    "ru" -> AppStrings(
        langCode = "ru",
        poziomica = "Уровень",
        libella = "Пузырьковый",
        menuBtn = "Меню",
        settingsBtn = "Настройки",
        closeBtn = "Закрыть",
        longitudinal = "ПРОДОЛЬНО",
        transverse = "ПОПЕРЕЧНО",
        remember = "Запомнить",
        clear = "Сброс",
        calibrated = "Откалибровано",
        notCalibrated = "Не откалибровано",
        rememberedLine = "Запомнено",
        longitudinalShort = "Прод.",
        transverseShort = "Попер.",
        settingsTitle = "Настройки",
        back = "Назад",
        appearance = "ВНЕШНИЙ ВИД",
        theme = "Тема",
        dark = "Тёмная",
        light = "Светлая",
        highContrastLabel = "Высокий контраст",
        highContrastSub = "Улучшает видимость (выше непрозрачность)",
        bubbleColorLabel = "Цвет пузырька",
        levelSignal = "СИГНАЛ УРОВНЯ",
        soundOnLevel = "Звук при уровне",
        soundOnLevelSub = "Сигнал при достижении 0°",
        vibrateOnLevel = "Вибрация при уровне",
        vibrateOnLevelSub = "Вибрация при достижении 0°",
        sensors = "ДАТЧИКИ",
        calibrateSensors = "Калибровать датчики",
        calibrationTitle = "Калибровка",
        howToCalibrate = "КАК КАЛИБРОВАТЬ",
        instrStep1 = "Положите уровень на плоскую поверхность.",
        instrStep2 = "Положите телефон на уровень.",
        instrStep3 = "Подождите, пока пузырёк не стабилизируется.",
        instrStep4 = "Нажмите 'Начать калибровку' - телефон запомнит эту настройку.",
        autoCalibration = "АВТОМАТИЧЕСКАЯ КАЛИБРОВКА",
        startCalibration = "Начать авто-калибровку",
        calibrating = "Калибровка…",
        calibratedSuccess = "Успешно откалибровано",
        manualCorrection = "РУЧНАЯ КАЛИБРОВКА",
        manualCorrectionSub = "Положите телефон горизонтально на традиционный уровень и вручную откорректируйте значения Pitch и Roll.",
        calibrationData = "ДАННЫЕ КАЛИБРОВКИ",
        pitchAxisLabel = "Продольная ось (Pitch)",
        rollAxisLabel = "Поперечная ось (Roll)",
        lastCalibration = "Последняя калибровка",
        resetCalibration = "Сбросить калибровку",
        menuTitle = "Меню",
        supportTitle = "Поддержать проект",
        supportText = "TrueBubble полностью бесплатна и не содержит рекламы. Мы разрабатываем её с энтузиазмом, чтобы она была доступна каждому.\nЕсли приложение оказалось полезным и вы хотите поддержать его развитие, посетите нашу страницу - любая помощь очень ценится.\nСпасибо за использование TrueBubble!",
        securityTitle = "Политика конфиденциальности",
        securityText = "TrueBubble не собирает личные данные. Все данные (калибровка, настройки) хранятся исключительно локально на устройстве и никогда не отправляются на внешние серверы.",
        gdprTitle = "Конфиденциальность данных",
        gdprText = "В соответствии с требованиями по защите данных:\n- Приложение не обрабатывает личные данные.\n- Куки и отслеживание не используются.\n- Данные калибровки полностью под контролем пользователя.\n- Удаление приложения удаляет все данные.",
        contactTitle = "Контакты / Сообщить об ошибке / Запрос функции",
        copiedToClipboard = "Скопировано в буфер обмена",
        compatTitle = "Совместимость с Android",
        versionLabel = "Версия",
        rateApp = "Оценить приложение",
        termsTitle = "Условия использования",
        termsBody = "Используя TrueBubble, вы соглашаетесь со следующим: приложение является вспомогательным измерительным инструментом (цифровой уровень) и не заменяет профессиональные измерительные приборы в задачах, требующих высокой точности. Вы несёте полную ответственность за то, как используете результаты измерений. Приложение предоставляется \"как есть\", без гарантии бесперебойной или безошибочной работы. Разработчик не несёт ответственности за ущерб, возникший из-за неточности измерений или неправильного использования приложения.",
        contactBody = "Нашли ошибку или есть идея для новой функции? Просто хотите поздороваться? Заполните короткую форму - каждое сообщение читается лично.",
        contactLinkLabel = "Открыть форму",
        privacyLinkLabel = "Открыть полную политику конфиденциальности",
    )

    "id" -> AppStrings(
        langCode = "id",
        poziomica = "Waterpass",
        libella = "Waterpass Lingkaran",
        menuBtn = "Menu",
        settingsBtn = "Pengaturan",
        closeBtn = "Tutup",
        longitudinal = "MEMBUJUR",
        transverse = "MELINTANG",
        remember = "Ingat",
        clear = "Hapus",
        calibrated = "Terkalibrasi",
        notCalibrated = "Belum dikalibrasi",
        rememberedLine = "Tersimpan",
        longitudinalShort = "Memb.",
        transverseShort = "Melin.",
        settingsTitle = "Pengaturan",
        back = "Kembali",
        appearance = "TAMPILAN",
        theme = "Tema",
        dark = "Gelap",
        light = "Terang",
        highContrastLabel = "Gelembung kontras tinggi",
        highContrastSub = "Meningkatkan visibilitas (opasitas lebih tinggi)",
        bubbleColorLabel = "Warna gelembung",
        levelSignal = "SINYAL LEVEL",
        soundOnLevel = "Suara saat level",
        soundOnLevelSub = "Sinyal saat mencapai 0°",
        vibrateOnLevel = "Getar saat level",
        vibrateOnLevelSub = "Getaran saat mencapai 0°",
        sensors = "SENSOR",
        calibrateSensors = "Kalibrasi sensor",
        calibrationTitle = "Kalibrasi",
        howToCalibrate = "CARA KALIBRASI",
        instrStep1 = "Letakkan waterpass di permukaan yang datar.",
        instrStep2 = "Letakkan ponsel di atas waterpass.",
        instrStep3 = "Tunggu hingga gelembung waterpass stabil.",
        instrStep4 = "Ketuk 'Mulai kalibrasi' - ponsel akan menyimpan pengaturan ini.",
        autoCalibration = "KALIBRASI OTOMATIS",
        startCalibration = "Mulai kalibrasi otomatis",
        calibrating = "Mengkalibrasi…",
        calibratedSuccess = "Berhasil dikalibrasi",
        manualCorrection = "KALIBRASI MANUAL",
        manualCorrectionSub = "Letakkan ponsel rata di atas waterpass tradisional dan koreksi nilai Pitch dan Roll secara manual.",
        calibrationData = "DATA KALIBRASI",
        pitchAxisLabel = "Sumbu membujur (Pitch)",
        rollAxisLabel = "Sumbu melintang (Roll)",
        lastCalibration = "Kalibrasi terakhir",
        resetCalibration = "Atur ulang kalibrasi",
        menuTitle = "Menu",
        supportTitle = "Dukung proyek",
        supportText = "TrueBubble sepenuhnya gratis dan bebas iklan. Kami mengembangkannya dengan penuh semangat agar dapat diakses oleh semua orang.\nJika aplikasi ini bermanfaat dan Anda ingin mendukung pengembangannya, kunjungi halaman kami - bantuan apa pun sangat kami hargai.\nTerima kasih telah menggunakan TrueBubble!",
        securityTitle = "Kebijakan Privasi",
        securityText = "TrueBubble tidak mengumpulkan data pribadi. Semua data (kalibrasi, pengaturan) disimpan hanya secara lokal di perangkat Anda dan tidak pernah dikirim ke server eksternal.",
        gdprTitle = "Privasi data",
        gdprText = "Sesuai dengan peraturan privasi:\n- Aplikasi tidak memproses data pribadi.\n- Tidak ada cookie atau pelacakan yang digunakan.\n- Data kalibrasi sepenuhnya di bawah kendali pengguna.\n- Menghapus instalasi aplikasi menghapus semua data.",
        contactTitle = "Kontak / Laporkan Bug / Permintaan Fitur",
        copiedToClipboard = "Disalin ke papan klip",
        compatTitle = "Kompatibilitas Android",
        versionLabel = "Versi",
        rateApp = "Nilai aplikasi",
        termsTitle = "Ketentuan layanan",
        termsBody = "Dengan menggunakan TrueBubble, Anda menyetujui hal berikut: aplikasi ini berfungsi sebagai alat ukur bantu (waterpass digital) dan tidak menggantikan alat ukur profesional untuk aplikasi yang memerlukan presisi tinggi. Anda sepenuhnya bertanggung jawab atas cara Anda menggunakan hasil pengukuran. Aplikasi disediakan \"apa adanya\", tanpa jaminan operasi tanpa gangguan atau bebas kesalahan. Pengembang tidak bertanggung jawab atas kerugian yang timbul akibat ketidakakuratan pengukuran atau penyalahgunaan aplikasi.",
        contactBody = "Menemukan bug atau punya ide untuk fitur baru? Hanya ingin menyapa? Isi formulir singkat - setiap pesan dibaca secara pribadi.",
        contactLinkLabel = "Buka formulir",
        privacyLinkLabel = "Lihat kebijakan privasi lengkap",
    )

    "ja" -> AppStrings(
        langCode = "ja",
        poziomica = "水準器",
        libella = "円形水準器",
        menuBtn = "メニュー",
        settingsBtn = "設定",
        closeBtn = "閉じる",
        longitudinal = "縦方向",
        transverse = "横方向",
        remember = "記憶",
        clear = "クリア",
        calibrated = "調整済み",
        notCalibrated = "未調整",
        rememberedLine = "記憶済み",
        longitudinalShort = "縦",
        transverseShort = "横",
        settingsTitle = "設定",
        back = "戻る",
        appearance = "外観",
        theme = "テーマ",
        dark = "ダーク",
        light = "ライト",
        highContrastLabel = "高コントラスト気泡",
        highContrastSub = "視認性向上（不透明度増加）",
        bubbleColorLabel = "気泡の色",
        levelSignal = "水準シグナル",
        soundOnLevel = "水準時の音",
        soundOnLevelSub = "0°達成時にシグナル",
        vibrateOnLevel = "水準時の振動",
        vibrateOnLevelSub = "0°達成時に振動",
        sensors = "センサー",
        calibrateSensors = "センサー調整",
        calibrationTitle = "調整",
        howToCalibrate = "調整方法",
        instrStep1 = "水準器を平らな面に置いてください。",
        instrStep2 = "スマートフォンを水準器の上に置いてください。",
        instrStep3 = "水準器の気泡が安定するまで待ちます。",
        instrStep4 = "「調整を開始」をタップ - スマートフォンがこの設定を保存します。",
        autoCalibration = "自動調整",
        startCalibration = "自動調整を開始",
        calibrating = "調整中…",
        calibratedSuccess = "調整完了",
        manualCorrection = "手動キャリブレーション",
        manualCorrectionSub = "従来の水準器の上にスマートフォンを水平に置き、PitchとRollの値を手動で調整してください。",
        calibrationData = "調整データ",
        pitchAxisLabel = "縦軸 (Pitch)",
        rollAxisLabel = "横軸 (Roll)",
        lastCalibration = "最終調整",
        resetCalibration = "調整をリセット",
        menuTitle = "メニュー",
        supportTitle = "プロジェクトを支援",
        supportText = "TrueBubbleは完全無料で広告なしのアプリです。誰もが使えるよう、情熱を持って開発しています。\n役に立った場合は、ぷれい私たちのページをご覧いただき、プロジェクトへのご支援をご検討ください。\nTrueBubbleをご利用いただきありがとうございます！",
        securityTitle = "プライバシーポリシー",
        securityText = "TrueBubbleは個人データを収集しません。すべてのデータ（調整、設定）はデバイスにのみローカルに保存され、外部サーバーに送信されることはありません。",
        gdprTitle = "データプライバシー",
        gdprText = "プライバシー規則に従い：\n- アプリは個人データを処理しません。\n- クッキーやトラッキングは使用しません。\n- 調整データはユーザーが完全に管理します。\n- アプリをアンインストールすると全データが削除されます。",
        contactTitle = "お問い合わせ / バグ報告 / 機能リクエスト",
        copiedToClipboard = "クリップボードにコピーしました",
        compatTitle = "Android互換性",
        versionLabel = "バージョン",
        rateApp = "アプリを評価する",
        termsTitle = "利用規約",
        termsBody = "TrueBubbleを使用することで、以下に同意したものとみなされます：本アプリは補助的な測定ツール（デジタル水準器）として機能し、高精度が求められる用途において専門的な測定機器の代替とはなりません。測定結果の利用方法についてはお客様が全責任を負うものとします。本アプリは「現状のまま」提供され、中断のない動作やエラーのない動作を保証するものではありません。開発者は、測定の不正確さやアプリの誤用に起因する損害について責任を負いません。",
        contactBody = "バグを見つけましたか、それとも新機能のアイデアがありますか？ただ挨拶したいだけでも構いません。短いフォームにご記入ください - すべてのメッセージは個人的に確認しています。",
        contactLinkLabel = "フォームを開く",
        privacyLinkLabel = "プライバシーポリシー全文を見る",
    )

    else -> AppStrings(  // "en" default
        langCode = "en",
        poziomica = "Level",
        libella = "Bullseye",
        menuBtn = "Menu",
        settingsBtn = "Settings",
        closeBtn = "Close",
        longitudinal = "LONGITUDINAL",
        transverse = "TRANSVERSE",
        remember = "Remember",
        clear = "Clear",
        calibrated = "Calibrated",
        notCalibrated = "Not calibrated",
        rememberedLine = "Remembered",
        longitudinalShort = "Long.",
        transverseShort = "Trans.",
        settingsTitle = "Settings",
        back = "Back",
        appearance = "APPEARANCE",
        theme = "Theme",
        dark = "Dark",
        light = "Light",
        highContrastLabel = "High contrast bubble",
        highContrastSub = "Improves visibility (higher opacity)",
        bubbleColorLabel = "Bubble color",
        levelSignal = "LEVEL SIGNAL",
        soundOnLevel = "Sound at level",
        soundOnLevelSub = "Signal when 0° is reached",
        vibrateOnLevel = "Vibration at level",
        vibrateOnLevelSub = "Vibration when 0° is reached",
        sensors = "SENSORS",
        calibrateSensors = "Calibrate sensors",
        calibrationTitle = "Calibration",
        howToCalibrate = "HOW TO CALIBRATE",
        instrStep1 = "Place a spirit level on a flat surface.",
        instrStep2 = "Place your phone on top of the spirit level.",
        instrStep3 = "Wait for the spirit level bubble to stabilize.",
        instrStep4 = "Tap 'Start calibration' - the phone will save this setting.",
        autoCalibration = "AUTO CALIBRATION",
        startCalibration = "Start auto calibration",
        calibrating = "Calibrating…",
        calibratedSuccess = "Calibrated successfully",
        manualCorrection = "MANUAL CALIBRATION",
        manualCorrectionSub = "Place the phone flat on a traditional spirit level and manually adjust the Pitch and Roll values.",
        calibrationData = "CALIBRATION DATA",
        pitchAxisLabel = "Longitudinal axis (Pitch)",
        rollAxisLabel = "Transverse axis (Roll)",
        lastCalibration = "Last calibration",
        resetCalibration = "Reset calibration",
        menuTitle = "Menu",
        supportTitle = "Support the project",
        supportText = "TrueBubble is completely free and ad-free. We develop it with passion to make it available to everyone.\nIf you find it useful and would like to support its development, please visit our page - any help is greatly appreciated and motivates us to keep improving.\nThank you for using TrueBubble!",
        securityTitle = "Privacy Policy",
        securityText = "TrueBubble does not collect any personal data. All data (calibration, settings) is stored locally on your device only and is never sent to any external servers.",
        gdprTitle = "GDPR & Data Privacy",
        gdprText = "In accordance with privacy regulations (GDPR EU 2016/679):\n- The app does not process personal data.\n- No cookies or tracking are used.\n- Calibration data is entirely under user control.\n- Uninstalling the app deletes all data.",
        contactTitle = "Contact / Report Bug / Feature Request",
        copiedToClipboard = "Copied to clipboard",
        compatTitle = "Android Compatibility",
        versionLabel = "Version",
        rateApp = "Rate the app",
        termsTitle = "Terms of Service",
        termsBody = "By using TrueBubble you agree to the following: the app is intended as an auxiliary measuring tool (digital spirit level) and does not replace professional measuring instruments in applications requiring high precision. You are fully responsible for how you use the measurement results. The app is provided \"as is\", without any warranty of uninterrupted or error-free operation. The developer is not liable for damages resulting from measurement inaccuracy or misuse of the app.",
        contactBody = "Found a bug or have an idea for a new feature? Just want to say hi? Fill out a short form - every message is read personally.",
        contactLinkLabel = "Open support form",
        privacyLinkLabel = "View full privacy policy",
    )
}
